[package]
name = "stylus-ai-greeter"
description = "AI Greeter example using Stylus"
version = "0.1.0"
edition = "2021"
license = "MIT"

[dependencies]
alloy-primitives = "=0.8.20"
alloy-sol-types = "=0.8.20"
stylus-sdk = "0.9.0"
hex = { version = "0.4", default-features = false }
# ort = "=2.0.0-rc.10"
# base64 = "0.21"
# cdc = "0.1.1"
md-5 = "0.10.6"
# ciborium = "0.2.2"
# borsh = "1.5.7"
# minicbor = { version = "2.1.1", features = ["derive"]}
# fastcdc = "3.2.1"
# ruzstd = { version = "0.8.1", default-features = false }
# hashbrown = { version = "0.16.0", default-features = true }
# libflate = "2.1.0"
# fxhash = "0.2.1"
# vector-map = "1.0.2"
# miniz_oxide = "0.8.9"
# bitcode = { version = "0.6.7", default-features = false, features = ["derive"] }
seq_chunking = "0.1.0"
rkyv = { version = "0.8.11", default-features = false, features = ["alloc","bytecheck"] }

[dev-dependencies]
alloy-primitives = { version = "=0.8.20", features = ["sha3-keccak"] }
tokio = { version = "1.12.0", features = ["full"] }
ethers = "2.0"
eyre = "0.6.8"
stylus-sdk = { version = "0.9.0", features = ["stylus-test"] }
dotenv = "0.15.0"
reqwest = { version = "0.12.23", default-features = true, features = ["blocking"] }
filebuffer = "1.0.0"
# cdchunking = "0.1"

[features]
default = ["mini-alloc"]
export-abi = ["stylus-sdk/export-abi"]
debug = ["stylus-sdk/debug"]
mini-alloc = ["stylus-sdk/mini-alloc"]

[[bin]]
name = "stylus-hello-world"
path = "src/main.rs"

[lib]
crate-type = ["lib", "cdylib"]

[profile.release]
codegen-units = 1        # prefer efficiency to compile time
panic = "abort"          # use simple panics
opt-level = "s"          # optimize for size ("s" may also work)
strip = true             # remove debug info
lto = true               # link time optimization
debug = false            # no debug data
rpath = false            # no run-time search path
debug-assertions = false # prune debug assertions
incremental = false      # no incremental builds
